trigger:
  branches:
    include:
    - master
    - features/*
    - bugfixes/*
  tags:
    exclude:    
    - v*   

pr:
- master

jobs:
- job: Test
  strategy:
    matrix:     
      2022:
        poolFlag: 2022
      2021:
        poolFlag: 2021
      2020:
        poolFlag: 2020
  timeoutInMinutes: 10
  pool:
    name: Autodesk
    demands: Civil3d  -equals $(poolFlag)
    
  steps:
  - checkout: self    
    clean: true
    fetchDepth: 1
  - task: NuGetToolInstaller@1
    inputs:      
      checkLatest: true
  - task: DownloadSecureFile@1
    name: nconf
    displayName: 'Download Nuget Config'
    inputs:
      secureFile: 'nuget.config'
  - script: |
      echo Moving $(nconf.secureFilePath) to the root directory $(System.DefaultWorkingDirectory)...
      xcopy $(nconf.secureFilePath) $(System.DefaultWorkingDirectory)      
      
  - task: DownloadSecureFile@1
    name: Cert
    displayName: 'Download Certificate'
    inputs:
      secureFile: 'CodeSigning2019.pfx'      
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $Secure_String_Pwd = ConvertTo-SecureString "Cedarbarn123" -AsPlainText -Force
        Import-PfxCertificate -FilePath $(Cert.secureFilePath) -CertStoreLocation Cert:\LocalMachine\My -Password $Secure_String_Pwd               
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'AcTestFramework.sln'   
      feedsToUse: 'config'
      nugetConfigPath: 'nuget.config'
      verbosityRestore: 'Normal'
      noCache: true   
  - task: VSBuild@1
    inputs:
      solution: 'AcTestFramework.sln'
      platform: 'x64'
      configuration: 'Release $(poolFlag)'
      clean: true
  - task: VisualStudioTestPlatformInstaller@1
    inputs:
      packageFeedSelector: 'nugetOrg'
      versionSelector: 'latestPreRelease'
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*Tests*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      uiTests: true
      otherConsoleOptions: '/platform:x64'